### ISSUE TITLE
Visual Studio build failure for OpenVX 1.2 sample implementation

### ISSUE THREAD

**Issue by ancahamuraru** [KhronosGroup/OpenVX-Registry#12]
OpenVX 1.2 sample implementation doesn't build with Visual Studio 2017.
Did anyone try to build it for Visual Studio?
As one can see from the output below, errors refer to
- doing pointer arithmetic with void*
- using arrays of variable size.

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2133	'ptr': unknown size	openvx-c_model-lib	C:\openvx_sample\kernels\c_model\c_copy.c	401	
Error	C2133	'space_weight': unknown size	openvx-c_model-lib	C:\openvx_sample\kernels\c_model\c_bilateral_filter.c	34	
Error	C2133	'space_weight': unknown size	openvx-c_model-lib	C:\openvx_sample\kernels\c_model\c_bilateral_filter.c	94	
Error	C2036	'void *': unknown size	openvx-c_model-lib	C:\openvx_sample\kernels\c_model\c_bilateral_filter.c	67	
Error	C2036	'void *': unknown size	openvx-c_model-lib	C:\openvx_sample\kernels\c_model\c_bilateral_filter.c	68	
Error	C2036	'void *': unknown size	openvx-c_model-lib	C:\openvx_sample\kernels\c_model\c_bilateral_filter.c	75	
Error	C2036	'void *': unknown size	openvx-c_model-lib	C:\openvx_sample\kernels\c_model\c_bilateral_filter.c	127	
Error	C2036	'void *': unknown size	openvx-c_model-lib	C:\openvx_sample\kernels\c_model\c_bilateral_filter.c	128	
Error	C2036	'void *': unknown size	openvx-c_model-lib	C:\openvx_sample\kernels\c_model\c_bilateral_filter.c	135	
Error	C2036	'void *': unknown size	openvx-c_model-lib	C:\openvx_sample\kernels\c_model\c_matchtemplate.c	287	
Error	C2036	'void *': unknown size	openvx-c_model-lib	C:\openvx_sample\kernels\c_model\c_matchtemplate.c	299	
Error	C2036	'void *': unknown size	openvx-c_model-lib	C:\openvx_sample\kernels\c_model\c_tensor_lut.c	34	
Error	C2036	'void *': unknown size	openvx-c_model-lib	C:\openvx_sample\kernels\c_model\c_tensor_lut.c	35	
Error	C2036	'void *': unknown size	openvx-c_model-lib	C:\openvx_sample\kernels\c_model\c_tensor_lut.c	45	
Error	C2036	'void *': unknown size	openvx-c_model-lib	C:\openvx_sample\kernels\c_model\c_tensor_lut.c	46	
Error	C2036	'void *': unknown size	openvx-c_model-lib	C:\openvx_sample\kernels\c_model\c_tensor_transpose.c	56	
Error	C2466	cannot allocate an array of constant size 0	openvx-c_model-lib	C:\openvx_sample\kernels\c_model\c_bilateral_filter.c	34	
Error	C2466	cannot allocate an array of constant size 0	openvx-c_model-lib	C:\openvx_sample\kernels\c_model\c_bilateral_filter.c	94	
Error	C2466	cannot allocate an array of constant size 0	openvx-c_model-lib	C:\openvx_sample\kernels\c_model\c_copy.c	401	
Error	LNK1181	cannot open input file '..\..\..\kernels\c_model\Debug\openvx-c_model-lib.lib'	openvx-c_model	C:\openvx_sampleBIN\sample\targets\c_model\LINK	1	
Error	C2057	expected constant expression	openvx-c_model-lib	C:\openvx_sample\kernels\c_model\c_bilateral_filter.c	34	
Error	C2057	expected constant expression	openvx-c_model-lib	C:\openvx_sample\kernels\c_model\c_bilateral_filter.c	94	
Error	C2057	expected constant expression	openvx-c_model-lib	C:\openvx_sample\kernels\c_model\c_copy.c	401

**Comment by tlepley** [comment]
Hi ancahamuraru. 

The sample implementation is primarily tested under Linux. Each target platform has its specificities and such issues may be detected each time the package is compiled for a new platform. 

I think that the simplest would be that:
1- you fix the issues you encounter locally (there is no hard problem to solve it seems)
2- you provide a patch file so that the Khronos group can update the internal OpenVX repo and then regenerate a Sample implementation package.

**Comment by fbrill3** [comment]
Revisions were made to the OpenVX 1.2 sample to address these warnings from Visual Studio, and an new package has been uploaded.  Closing.
