### ISSUE TITLE
MatchTemplate function

### ISSUE THREAD

**Issue by egorovp** [KhronosGroup/OpenVX-Registry#29]
# Problem:
Error in the dimensions of the output map in CTS(OpenVX Conformance Test Suite).

Quote from [standard](https://www.khronos.org/registry/OpenVX/specs/1.2.1/OpenVX_Specification_1_2_1.html#vxMatchTemplateNode):
> The output of the template matching node is a comparison map. The output comparison map should be the same size as the input image.

Why in CTS the output map has following dimensions:

[result_width](https://github.com/KhronosGroup/OpenVX-cts/blob/207d3019de5715906cad64ad4ce36e17c643fcd4/test_conformance/test_matchtemplate.c#L85) = ```source_width - template_width + 1``` ,
[result_height](https://github.com/KhronosGroup/OpenVX-cts/blob/207d3019de5715906cad64ad4ce36e17c643fcd4/test_conformance/test_matchtemplate.c#L85) = ```source_height - template_height + 1```

instead of  ```(source_width, source_height)``` ?

# Links:
1. [Standard](https://www.khronos.org/registry/OpenVX/specs/1.2.1/OpenVX_Specification_1_2_1.html#vxMatchTemplateNode)
2. [Conformance Tests](https://github.com/KhronosGroup/OpenVX-cts/blob/207d3019de5715906cad64ad4ce36e17c643fcd4/test_conformance/test_matchtemplate.c#L85)

**Comment by rgolovanov** [comment]
@oddhack could you please help to resolve issues #29,#30,#31,#31. Looks like a common problem is in differences between standard and CTS. We completely implemented OpenVX 1.2 but these issues are interfere with passing CTS, so we cannot officially say that our library is conformant to OpenVX 1.2.

**Comment by oddhack** [comment]
@rgolovanov this is a spec issue, so it needs to be dealt with by the OpenVX Working Group, not by me (I just provide infrastructure support and manage the registry for the WG). The WG is aware of these issues and they've asked a couple of members to respond to them, so hopefully you'll get some feedback soon.

For spec issues going forward, please file in https://github.com/KhronosGroup/OpenVX-api-docs , which is the spec repository - this repo is just a publishing mechanism.

**Comment by egorovp** [comment]
moved to [link](https://github.com/KhronosGroup/OpenVX-api-docs/issues/3)

**Comment by rgolovanov** [comment]
@oddhack thanks a lot !

**Comment by egorovp** [comment]
@oddhack thank you

**Comment by fbrill3** [comment]
Closing this item since it's moved to https://github.com/KhronosGroup/OpenVX-api-docs/issues/3
