### ISSUE TITLE
BilateralFilter function

### ISSUE THREAD

**Issue by egorovp** [KhronosGroup/OpenVX-Registry#30]
# Problem

1) The input tensor may have 2 or 3 dimensions.
In case of 3 dimensions the size of the first dimension can be 1 or 2.
Why it can be changed [from 1 to 20 in CTS](
https://github.com/KhronosGroup/OpenVX-cts/blob/207d3019de5715906cad64ad4ce36e17c643fcd4/test_conformance/test_bilateralfilter.c#L300)?
2) According to documentation supported border mode shall be replicate or constant. Why it is set to [undefined](https://github.com/KhronosGroup/OpenVX-cts/blob/207d3019de5715906cad64ad4ce36e17c643fcd4/test_conformance/test_bilateralfilter.c#L152) in CTS? Since it is undefined in CTS, then why the resulting values of borders are still checked?
4) In case of 3 dimensions the first dimension is "radiometric" and the filtering goes by summing averaged weighted pixels in the window.
Weight for every pixel in the window depends on the distance to the center of the window and on the difference in radiometric space between these two pixels.
Why is radiometric space ignored in CTS?

# Links
1) [Standard](https://www.khronos.org/registry/OpenVX/specs/1.2.1/OpenVX_Specification_1_2_1.html#group_vision_function_bilateral_filter)
2) [Conformance Tests](https://github.com/KhronosGroup/OpenVX-cts/blob/openvx_1.2/test_conformance/test_bilateralfilter.c)

**Comment by egorovp** [comment]
moved to [link](https://github.com/KhronosGroup/OpenVX-api-docs/issues/4)

**Comment by fbrill3** [comment]
Closing this items since it's moved to https://github.com/KhronosGroup/OpenVX-api-docs/issues/4
