### ISSUE TITLE
HOGCells function

### ISSUE THREAD

**Issue by egorovp** [KhronosGroup/OpenVX-Registry#31]
# Problem
Type error of the output tensor.

[Documentation](https://www.khronos.org/registry/OpenVX/specs/1.2.1/OpenVX_Specification_1_2_1.html#_vxhogcellsnode) says that the type of the output tensor ```bins``` of vxHOGCellsNode function is ```VX_TYPE_INT16```.
But [there is ```VX_TYPE_INT8```](https://github.com/KhronosGroup/OpenVX-cts/blob/207d3019de5715906cad64ad4ce36e17c643fcd4/test_conformance/test_hog.c#L51) for ```bins``` in CTS.

# Links

1) [Standard](https://www.khronos.org/registry/OpenVX/specs/1.2.1/OpenVX_Specification_1_2_1.html#_vxhogcellsnode)
2) [Conformance Tests](https://github.com/KhronosGroup/OpenVX-cts/blob/207d3019de5715906cad64ad4ce36e17c643fcd4/test_conformance/test_hog.c#L51)

**Comment by egorovp** [comment]
moved to [link](https://github.com/KhronosGroup/OpenVX-api-docs/issues/5)

**Comment by fbrill3** [comment]
Closing this item since it's moved to https://github.com/KhronosGroup/OpenVX-api-docs/issues/5
