### ISSUE TITLE
HOGFeatures function

### ISSUE THREAD

**Issue by egorovp** [KhronosGroup/OpenVX-Registry#32]
# Problem

1) Why the third features' dimension aren't the same in [CTS](https://github.com/KhronosGroup/OpenVX-cts/blob/207d3019de5715906cad64ad4ce36e17c643fcd4/test_conformance/test_hog.c#L374) and in [documentation](https://www.khronos.org/registry/OpenVX/specs/1.2.1/OpenVX_Specification_1_2_1.html#_vxhogfeaturesnode)? (therefore, the further formation of the output tensor is incorrect)
    >e.g. in CTS for the size of the third features' dimension it's not enough multiplication by ```(cells_per_block_w * cells_per_block_h)```
2) In CTS ```TEST(HogFeatures, testNodeCreation)```: why ```bins_dims``` [is passed](https://github.com/KhronosGroup/OpenVX-cts/blob/207d3019de5715906cad64ad4ce36e17c643fcd4/test_conformance/test_hog.c#L314) instead of ```features'``` dimensions?

# Links

1) [Standard](https://www.khronos.org/registry/OpenVX/specs/1.2.1/OpenVX_Specification_1_2_1.html#_vxhogfeaturesnode)
2) [Conformance Tests](https://github.com/KhronosGroup/OpenVX-cts/blob/207d3019de5715906cad64ad4ce36e17c643fcd4/test_conformance/test_hog.c#L281)

**Comment by egorovp** [comment]
moved to [link](https://github.com/KhronosGroup/OpenVX-api-docs/issues/6)

**Comment by fbrill3** [comment]
Closing this item since it's moved to https://github.com/KhronosGroup/OpenVX-api-docs/issues/6
