### ISSUE TITLE
README.md SVN link Forbidden Access

### ISSUE THREAD

**Issue by outofcontrol** [KhronosGroup/OpenVX-Registry#39]
Clicking on the link on the README.md page in the OpenVX-Registry (https://cvs.khronos.org/svn/repos/registry/trunk/public/vx/) results in a page with Forbidden access. The permissions in Subversion are set to '* = ', resulting in no one having read access. Suggest we either remove the link or adjust the permissions on the SVN VM.

**Comment by oddhack** [comment]
Let's just make it readable for now. That repo contains older VX spec sources, IIRC, and they aren't anywhere in public github.

**Comment by outofcontrol** [comment]
SVN permissions have been updated and the link now works.
