### ISSUE TITLE
enum values  VX_CONTEXT_TARGETS and VX_CONTEXT_IMMEDIATE_BORDER_POLICY are equal

### ISSUE THREAD

**Issue by sheldonrobinson** [KhronosGroup/OpenVX-Registry#5]
Issue in openvx_sample_1.1.tar.bz2 
VX_CONTEXT_TARGETS defined at openvx_sample/include/VX/vx_ext_target.h, line 57 as :
`VX_CONTEXT_TARGETS = VX_ATTRIBUTE_BASE(VX_ID_KHRONOS, VX_TYPE_CONTEXT) + 0xC`

VX_CONTEXT_TARGETS defined at openvx_sample/include/VX/vx_types.h, line 806 as :
`VX_CONTEXT_IMMEDIATE_BORDER_POLICY = VX_ATTRIBUTE_BASE(VX_ID_KHRONOS, VX_TYPE_CONTEXT) + 0xC`

Fix:
VX_CONTEXT_TARGETS defined at openvx_sample/include/VX/vx_ext_target.h, line 57 should be : 
 `VX_CONTEXT_TARGETS = VX_ATTRIBUTE_BASE(VX_ID_KHRONOS, VX_TYPE_TARGET) + 0xC`

**Comment by fbrill3** [comment]
This issue is fixed in the OpenVX 1.2 sample code.  Will not fix for OpenVX 1.1 and earlier.
